@echo off 
if exist .\"Send MTM Emails" (
    rmdir /s /q "Send MTM Emails"
    echo. && echo Deleted original folder of "Send MTM Emails"! && echo.
)
REM Make sure that pyinstaller is installed in your system!
pyinstaller --onedir email-script.py --name "Send MTM Emails" && echo. && echo Successfully created the executable file for Send MTM Emails!
move dist\"Send MTM Emails" . && echo. && echo Moved directory successfully!
rmdir dist && echo. && echo Successfully removed dist folder...
rmdir /s /q build && echo. && echo Successfully removed build folder...
rmdir /s /q __pycache__ && echo. && echo Successfully removed __pycache__ folder...
del *.spec && echo. && echo Successfully removed the spec file...