@echo off 
if exist .\"Change Password of Encrypted File" (
    rmdir /s /q "Change Password of Encrypted File"
    echo. && echo Deleted original folder of "Change Password of Encrypted File"! && echo.
)
REM Make sure that pyinstaller is installed in your system!
pyinstaller --onedir change-encrypted-excel-file-password.py --name "Change Password of Encrypted File" && echo. && echo Successfully created the executable file for Change Password of Encrypted File!
move dist\"Change Password of Encrypted File" . && echo. && echo Moved directory successfully!
rmdir dist && echo. && echo Successfully removed dist folder...
rmdir /s /q build && echo. && echo Successfully removed build folder...
rmdir /s /q __pycache__ && echo. && echo Successfully removed __pycache__ folder...
del *.spec && echo. && echo Successfully removed the spec file...