@echo off 
if exist .\"Change Pivot Price File Name" (
    rmdir /s /q "Change Pivot Price File Name"
    echo. && echo Deleted original folder of "Change Pivot Price File Name"! && echo.
)
REM Make sure that pyinstaller is installed in your system!
pyinstaller --onedir rename-pivot-price-file.py --name "Change Pivot Price File Name" && echo. && echo Successfully created the executable file for Change Pivot Price File Name!
move dist\"Change Pivot Price File Name" . && echo. && echo Moved directory successfully!
rmdir dist && echo. && echo Successfully removed dist folder...
rmdir /s /q build && echo. && echo Successfully removed build folder...
rmdir /s /q __pycache__ && echo. && echo Successfully removed __pycache__ folder...
del *.spec && echo. && echo Successfully removed the spec file...